version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trendyyleads-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: trendyyleads
      POSTGRES_PASSWORD: trendyyleads_dev
      POSTGRES_DB: trendyyleads
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trendyyleads-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://trendyyleads:trendyyleads_dev@postgres:5437/trendyyleads
      - JWT_SECRET=FKIoGNN+v8YQ83x0C2v8t3ci3q6CusABBjTa7KJqs8s=
      - PAYSTACK_SECRET_KEY=sk_live_a5c69eb20aec8b812af0d1d3c7c20173de8728cb
      - PORT=3001
      - FRONTEND_URL=http://localhost:3002
    ports:
      - '127.0.0.1:3001:3001'
    depends_on:
      - postgres
    # Run migrations then start
    command: >
      sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001
    container_name: trendyyleads-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - '127.0.0.1:3002:3000'
    depends_on:
      - backend

volumes:
  pgdata:
